name: Render CV

on:
  workflow_dispatch:

env:
  USER_EMAIL: bambanggunawan887@gmail.com
  USER_NAME: bambanggunawanid

jobs:
  rendercv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install RenderCV
        run: pip install rendercv[full]

      - name: Render CV
        run: |
          make render

      - name: Commit and Push Rendered PDF
        run: |
          git config --local user.email "${{ env.USER_EMAIL }}"
          git config --local user.name "${{ env.USER_NAME }}"

          PDF_YEAR=$(date +"%Y")
          OUTPUT_PDF="Bambang_Gunawan_CV_${PDF_YEAR}.pdf"

          git add "${OUTPUT_PDF}"
          git add rendercv_output
          git commit -m "chore: update rendered PDF [skip ci]" || exit 0
          git push
